// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKe1ttcb8EOOZWpMEearFYRfV4CLlB90',
    appId: '1:530685758397:web:a2db47bef0b684af4ae0d4',
    messagingSenderId: '530685758397',
    projectId: 'prism-system-techno',
    authDomain: 'prism-system-techno.firebaseapp.com',
    storageBucket: 'prism-system-techno.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5YVjE7qORmc3V7S7Y9n9NbCAgZNT_w4',
    appId: '1:530685758397:android:77d5626bae4347e94ae0d4',
    messagingSenderId: '530685758397',
    projectId: 'prism-system-techno',
    storageBucket: 'prism-system-techno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTtHw3O4QA5AcXKHXJtYCg8H6sQlDkYLU',
    appId: '1:530685758397:ios:1e024d8117ef60544ae0d4',
    messagingSenderId: '530685758397',
    projectId: 'prism-system-techno',
    storageBucket: 'prism-system-techno.firebasestorage.app',
    iosBundleId: 'com.example.prismSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTtHw3O4QA5AcXKHXJtYCg8H6sQlDkYLU',
    appId: '1:530685758397:ios:1e024d8117ef60544ae0d4',
    messagingSenderId: '530685758397',
    projectId: 'prism-system-techno',
    storageBucket: 'prism-system-techno.firebasestorage.app',
    iosBundleId: 'com.example.prismSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATKe1ttcb8EOOZWpMEearFYRfV4CLlB90',
    appId: '1:530685758397:web:f877bae1348fb6fe4ae0d4',
    messagingSenderId: '530685758397',
    projectId: 'prism-system-techno',
    authDomain: 'prism-system-techno.firebaseapp.com',
    storageBucket: 'prism-system-techno.firebasestorage.app',
  );
}
